const db = require("../models");

const seedVehicles = async () => {
  try {
    await db.Vehicle.bulkCreate(
      [
        // Western Province — 24 vehicles (WP-3-0001 to WP-3-0024)
        { registration_number: "WP-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000001", engine_number: "ENG000001", status: "ACTIVE" },
        { registration_number: "WP-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000002", engine_number: "ENG000002", status: "ACTIVE" },
        { registration_number: "WP-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000003", engine_number: "ENG000003", status: "ACTIVE" },
        { registration_number: "WP-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000004", engine_number: "ENG000004", status: "ACTIVE" },
        { registration_number: "WP-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000005", engine_number: "ENG000005", status: "INACTIVE" },
        { registration_number: "WP-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000006", engine_number: "ENG000006", status: "ACTIVE" },
        { registration_number: "WP-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000007", engine_number: "ENG000007", status: "ACTIVE" },
        { registration_number: "WP-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000008", engine_number: "ENG000008", status: "ACTIVE" },
        { registration_number: "WP-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000009", engine_number: "ENG000009", status: "ACTIVE" },
        { registration_number: "WP-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000010", engine_number: "ENG000010", status: "UNDER_MAINTENANCE" },
        { registration_number: "WP-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000011", engine_number: "ENG000011", status: "ACTIVE" },
        { registration_number: "WP-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000012", engine_number: "ENG000012", status: "ACTIVE" },
        { registration_number: "WP-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000013", engine_number: "ENG000013", status: "ACTIVE" },
        { registration_number: "WP-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000014", engine_number: "ENG000014", status: "ACTIVE" },
        { registration_number: "WP-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000015", engine_number: "ENG000015", status: "INACTIVE" },
        { registration_number: "WP-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000016", engine_number: "ENG000016", status: "ACTIVE" },
        { registration_number: "WP-3-0017", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000017", engine_number: "ENG000017", status: "ACTIVE" },
        { registration_number: "WP-3-0018", vehicle_type: "Three Wheeler", model: "TVS King", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000018", engine_number: "ENG000018", status: "ACTIVE" },
        { registration_number: "WP-3-0019", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000019", engine_number: "ENG000019", status: "ACTIVE" },
        { registration_number: "WP-3-0020", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000020", engine_number: "ENG000020", status: "UNDER_MAINTENANCE" },
        { registration_number: "WP-3-0021", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000021", engine_number: "ENG000021", status: "ACTIVE" },
        { registration_number: "WP-3-0022", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000022", engine_number: "ENG000022", status: "ACTIVE" },
        { registration_number: "WP-3-0023", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000023", engine_number: "ENG000023", status: "ACTIVE" },
        { registration_number: "WP-3-0024", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000024", engine_number: "ENG000024", status: "ACTIVE" },

        // Central Province — 24 vehicles (CP-3-0001 to CP-3-0024)
        { registration_number: "CP-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000025", engine_number: "ENG000025", status: "INACTIVE" },
        { registration_number: "CP-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000026", engine_number: "ENG000026", status: "ACTIVE" },
        { registration_number: "CP-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000027", engine_number: "ENG000027", status: "ACTIVE" },
        { registration_number: "CP-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000028", engine_number: "ENG000028", status: "ACTIVE" },
        { registration_number: "CP-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000029", engine_number: "ENG000029", status: "ACTIVE" },
        { registration_number: "CP-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000030", engine_number: "ENG000030", status: "UNDER_MAINTENANCE" },
        { registration_number: "CP-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000031", engine_number: "ENG000031", status: "ACTIVE" },
        { registration_number: "CP-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000032", engine_number: "ENG000032", status: "ACTIVE" },
        { registration_number: "CP-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000033", engine_number: "ENG000033", status: "ACTIVE" },
        { registration_number: "CP-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000034", engine_number: "ENG000034", status: "ACTIVE" },
        { registration_number: "CP-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000035", engine_number: "ENG000035", status: "INACTIVE" },
        { registration_number: "CP-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000036", engine_number: "ENG000036", status: "ACTIVE" },
        { registration_number: "CP-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000037", engine_number: "ENG000037", status: "ACTIVE" },
        { registration_number: "CP-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000038", engine_number: "ENG000038", status: "ACTIVE" },
        { registration_number: "CP-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000039", engine_number: "ENG000039", status: "ACTIVE" },
        { registration_number: "CP-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000040", engine_number: "ENG000040", status: "UNDER_MAINTENANCE" },
        { registration_number: "CP-3-0017", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000041", engine_number: "ENG000041", status: "ACTIVE" },
        { registration_number: "CP-3-0018", vehicle_type: "Three Wheeler", model: "TVS King", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000042", engine_number: "ENG000042", status: "ACTIVE" },
        { registration_number: "CP-3-0019", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000043", engine_number: "ENG000043", status: "ACTIVE" },
        { registration_number: "CP-3-0020", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000044", engine_number: "ENG000044", status: "ACTIVE" },
        { registration_number: "CP-3-0021", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000045", engine_number: "ENG000045", status: "INACTIVE" },
        { registration_number: "CP-3-0022", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000046", engine_number: "ENG000046", status: "ACTIVE" },
        { registration_number: "CP-3-0023", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000047", engine_number: "ENG000047", status: "ACTIVE" },
        { registration_number: "CP-3-0024", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000048", engine_number: "ENG000048", status: "ACTIVE" },

        // Southern Province — 24 vehicles (SP-3-0001 to SP-3-0024)
        { registration_number: "SP-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000049", engine_number: "ENG000049", status: "ACTIVE" },
        { registration_number: "SP-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000050", engine_number: "ENG000050", status: "UNDER_MAINTENANCE" },
        { registration_number: "SP-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000051", engine_number: "ENG000051", status: "ACTIVE" },
        { registration_number: "SP-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000052", engine_number: "ENG000052", status: "ACTIVE" },
        { registration_number: "SP-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000053", engine_number: "ENG000053", status: "ACTIVE" },
        { registration_number: "SP-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000054", engine_number: "ENG000054", status: "ACTIVE" },
        { registration_number: "SP-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000055", engine_number: "ENG000055", status: "INACTIVE" },
        { registration_number: "SP-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000056", engine_number: "ENG000056", status: "ACTIVE" },
        { registration_number: "SP-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000057", engine_number: "ENG000057", status: "ACTIVE" },
        { registration_number: "SP-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000058", engine_number: "ENG000058", status: "ACTIVE" },
        { registration_number: "SP-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000059", engine_number: "ENG000059", status: "ACTIVE" },
        { registration_number: "SP-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000060", engine_number: "ENG000060", status: "UNDER_MAINTENANCE" },
        { registration_number: "SP-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000061", engine_number: "ENG000061", status: "ACTIVE" },
        { registration_number: "SP-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000062", engine_number: "ENG000062", status: "ACTIVE" },
        { registration_number: "SP-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000063", engine_number: "ENG000063", status: "ACTIVE" },
        { registration_number: "SP-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000064", engine_number: "ENG000064", status: "ACTIVE" },
        { registration_number: "SP-3-0017", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000065", engine_number: "ENG000065", status: "INACTIVE" },
        { registration_number: "SP-3-0018", vehicle_type: "Three Wheeler", model: "TVS King", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000066", engine_number: "ENG000066", status: "ACTIVE" },
        { registration_number: "SP-3-0019", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000067", engine_number: "ENG000067", status: "ACTIVE" },
        { registration_number: "SP-3-0020", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000068", engine_number: "ENG000068", status: "ACTIVE" },
        { registration_number: "SP-3-0021", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000069", engine_number: "ENG000069", status: "ACTIVE" },
        { registration_number: "SP-3-0022", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000070", engine_number: "ENG000070", status: "UNDER_MAINTENANCE" },
        { registration_number: "SP-3-0023", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000071", engine_number: "ENG000071", status: "ACTIVE" },
        { registration_number: "SP-3-0024", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000072", engine_number: "ENG000072", status: "ACTIVE" },

        // Northern Province — 40 vehicles (NP-3-0001 to NP-3-0040)
        { registration_number: "NP-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000073", engine_number: "ENG000073", status: "ACTIVE" },
        { registration_number: "NP-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000074", engine_number: "ENG000074", status: "ACTIVE" },
        { registration_number: "NP-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000075", engine_number: "ENG000075", status: "INACTIVE" },
        { registration_number: "NP-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000076", engine_number: "ENG000076", status: "ACTIVE" },
        { registration_number: "NP-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000077", engine_number: "ENG000077", status: "ACTIVE" },
        { registration_number: "NP-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000078", engine_number: "ENG000078", status: "ACTIVE" },
        { registration_number: "NP-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000079", engine_number: "ENG000079", status: "ACTIVE" },
        { registration_number: "NP-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000080", engine_number: "ENG000080", status: "UNDER_MAINTENANCE" },
        { registration_number: "NP-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000081", engine_number: "ENG000081", status: "ACTIVE" },
        { registration_number: "NP-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000082", engine_number: "ENG000082", status: "ACTIVE" },
        { registration_number: "NP-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000083", engine_number: "ENG000083", status: "ACTIVE" },
        { registration_number: "NP-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000084", engine_number: "ENG000084", status: "ACTIVE" },
        { registration_number: "NP-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000085", engine_number: "ENG000085", status: "INACTIVE" },
        { registration_number: "NP-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000086", engine_number: "ENG000086", status: "ACTIVE" },
        { registration_number: "NP-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000087", engine_number: "ENG000087", status: "ACTIVE" },
        { registration_number: "NP-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000088", engine_number: "ENG000088", status: "ACTIVE" },
        { registration_number: "NP-3-0017", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000089", engine_number: "ENG000089", status: "ACTIVE" },
        { registration_number: "NP-3-0018", vehicle_type: "Three Wheeler", model: "TVS King", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000090", engine_number: "ENG000090", status: "UNDER_MAINTENANCE" },
        { registration_number: "NP-3-0019", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000091", engine_number: "ENG000091", status: "ACTIVE" },
        { registration_number: "NP-3-0020", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000092", engine_number: "ENG000092", status: "ACTIVE" },
        { registration_number: "NP-3-0021", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000093", engine_number: "ENG000093", status: "ACTIVE" },
        { registration_number: "NP-3-0022", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000094", engine_number: "ENG000094", status: "ACTIVE" },
        { registration_number: "NP-3-0023", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000095", engine_number: "ENG000095", status: "INACTIVE" },
        { registration_number: "NP-3-0024", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000096", engine_number: "ENG000096", status: "ACTIVE" },
        { registration_number: "NP-3-0025", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000097", engine_number: "ENG000097", status: "ACTIVE" },
        { registration_number: "NP-3-0026", vehicle_type: "Three Wheeler", model: "TVS King", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000098", engine_number: "ENG000098", status: "ACTIVE" },
        { registration_number: "NP-3-0027", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000099", engine_number: "ENG000099", status: "ACTIVE" },
        { registration_number: "NP-3-0028", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000100", engine_number: "ENG000100", status: "UNDER_MAINTENANCE" },
        { registration_number: "NP-3-0029", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000101", engine_number: "ENG000101", status: "ACTIVE" },
        { registration_number: "NP-3-0030", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000102", engine_number: "ENG000102", status: "ACTIVE" },
        { registration_number: "NP-3-0031", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000103", engine_number: "ENG000103", status: "ACTIVE" },
        { registration_number: "NP-3-0032", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000104", engine_number: "ENG000104", status: "ACTIVE" },
        { registration_number: "NP-3-0033", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000105", engine_number: "ENG000105", status: "INACTIVE" },
        { registration_number: "NP-3-0034", vehicle_type: "Three Wheeler", model: "TVS King", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000106", engine_number: "ENG000106", status: "ACTIVE" },
        { registration_number: "NP-3-0035", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000107", engine_number: "ENG000107", status: "ACTIVE" },
        { registration_number: "NP-3-0036", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000108", engine_number: "ENG000108", status: "ACTIVE" },
        { registration_number: "NP-3-0037", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000109", engine_number: "ENG000109", status: "ACTIVE" },
        { registration_number: "NP-3-0038", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000110", engine_number: "ENG000110", status: "UNDER_MAINTENANCE" },
        { registration_number: "NP-3-0039", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000111", engine_number: "ENG000111", status: "ACTIVE" },
        { registration_number: "NP-3-0040", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000112", engine_number: "ENG000112", status: "ACTIVE" },

        // Eastern Province — 24 vehicles (EP-3-0001 to EP-3-0024)
        { registration_number: "EP-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000113", engine_number: "ENG000113", status: "ACTIVE" },
        { registration_number: "EP-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000114", engine_number: "ENG000114", status: "ACTIVE" },
        { registration_number: "EP-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000115", engine_number: "ENG000115", status: "INACTIVE" },
        { registration_number: "EP-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000116", engine_number: "ENG000116", status: "ACTIVE" },
        { registration_number: "EP-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000117", engine_number: "ENG000117", status: "ACTIVE" },
        { registration_number: "EP-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000118", engine_number: "ENG000118", status: "ACTIVE" },
        { registration_number: "EP-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000119", engine_number: "ENG000119", status: "ACTIVE" },
        { registration_number: "EP-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000120", engine_number: "ENG000120", status: "UNDER_MAINTENANCE" },
        { registration_number: "EP-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000121", engine_number: "ENG000121", status: "ACTIVE" },
        { registration_number: "EP-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000122", engine_number: "ENG000122", status: "ACTIVE" },
        { registration_number: "EP-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000123", engine_number: "ENG000123", status: "ACTIVE" },
        { registration_number: "EP-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000124", engine_number: "ENG000124", status: "ACTIVE" },
        { registration_number: "EP-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000125", engine_number: "ENG000125", status: "INACTIVE" },
        { registration_number: "EP-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000126", engine_number: "ENG000126", status: "ACTIVE" },
        { registration_number: "EP-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000127", engine_number: "ENG000127", status: "ACTIVE" },
        { registration_number: "EP-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000128", engine_number: "ENG000128", status: "ACTIVE" },
        { registration_number: "EP-3-0017", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000129", engine_number: "ENG000129", status: "ACTIVE" },
        { registration_number: "EP-3-0018", vehicle_type: "Three Wheeler", model: "TVS King", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000130", engine_number: "ENG000130", status: "UNDER_MAINTENANCE" },
        { registration_number: "EP-3-0019", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000131", engine_number: "ENG000131", status: "ACTIVE" },
        { registration_number: "EP-3-0020", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000132", engine_number: "ENG000132", status: "ACTIVE" },
        { registration_number: "EP-3-0021", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000133", engine_number: "ENG000133", status: "ACTIVE" },
        { registration_number: "EP-3-0022", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000134", engine_number: "ENG000134", status: "ACTIVE" },
        { registration_number: "EP-3-0023", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000135", engine_number: "ENG000135", status: "INACTIVE" },
        { registration_number: "EP-3-0024", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000136", engine_number: "ENG000136", status: "ACTIVE" },

        // North Western Province — 16 vehicles (NW-3-0001 to NW-3-0016)
        { registration_number: "NW-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000137", engine_number: "ENG000137", status: "ACTIVE" },
        { registration_number: "NW-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000138", engine_number: "ENG000138", status: "ACTIVE" },
        { registration_number: "NW-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000139", engine_number: "ENG000139", status: "ACTIVE" },
        { registration_number: "NW-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000140", engine_number: "ENG000140", status: "UNDER_MAINTENANCE" },
        { registration_number: "NW-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000141", engine_number: "ENG000141", status: "ACTIVE" },
        { registration_number: "NW-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000142", engine_number: "ENG000142", status: "ACTIVE" },
        { registration_number: "NW-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000143", engine_number: "ENG000143", status: "ACTIVE" },
        { registration_number: "NW-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000144", engine_number: "ENG000144", status: "ACTIVE" },
        { registration_number: "NW-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000145", engine_number: "ENG000145", status: "INACTIVE" },
        { registration_number: "NW-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000146", engine_number: "ENG000146", status: "ACTIVE" },
        { registration_number: "NW-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000147", engine_number: "ENG000147", status: "ACTIVE" },
        { registration_number: "NW-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000148", engine_number: "ENG000148", status: "ACTIVE" },
        { registration_number: "NW-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000149", engine_number: "ENG000149", status: "ACTIVE" },
        { registration_number: "NW-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000150", engine_number: "ENG000150", status: "UNDER_MAINTENANCE" },
        { registration_number: "NW-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000151", engine_number: "ENG000151", status: "ACTIVE" },
        { registration_number: "NW-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000152", engine_number: "ENG000152", status: "ACTIVE" },

        // North Central Province — 16 vehicles (NC-3-0001 to NC-3-0016)
        { registration_number: "NC-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000153", engine_number: "ENG000153", status: "ACTIVE" },
        { registration_number: "NC-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000154", engine_number: "ENG000154", status: "ACTIVE" },
        { registration_number: "NC-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000155", engine_number: "ENG000155", status: "INACTIVE" },
        { registration_number: "NC-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000156", engine_number: "ENG000156", status: "ACTIVE" },
        { registration_number: "NC-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000157", engine_number: "ENG000157", status: "ACTIVE" },
        { registration_number: "NC-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000158", engine_number: "ENG000158", status: "ACTIVE" },
        { registration_number: "NC-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000159", engine_number: "ENG000159", status: "ACTIVE" },
        { registration_number: "NC-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000160", engine_number: "ENG000160", status: "UNDER_MAINTENANCE" },
        { registration_number: "NC-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000161", engine_number: "ENG000161", status: "ACTIVE" },
        { registration_number: "NC-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000162", engine_number: "ENG000162", status: "ACTIVE" },
        { registration_number: "NC-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000163", engine_number: "ENG000163", status: "ACTIVE" },
        { registration_number: "NC-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000164", engine_number: "ENG000164", status: "ACTIVE" },
        { registration_number: "NC-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000165", engine_number: "ENG000165", status: "INACTIVE" },
        { registration_number: "NC-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000166", engine_number: "ENG000166", status: "ACTIVE" },
        { registration_number: "NC-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000167", engine_number: "ENG000167", status: "ACTIVE" },
        { registration_number: "NC-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000168", engine_number: "ENG000168", status: "ACTIVE" },

        // Uva Province — 16 vehicles (UV-3-0001 to UV-3-0016)
        { registration_number: "UV-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000169", engine_number: "ENG000169", status: "ACTIVE" },
        { registration_number: "UV-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000170", engine_number: "ENG000170", status: "UNDER_MAINTENANCE" },
        { registration_number: "UV-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000171", engine_number: "ENG000171", status: "ACTIVE" },
        { registration_number: "UV-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000172", engine_number: "ENG000172", status: "ACTIVE" },
        { registration_number: "UV-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000173", engine_number: "ENG000173", status: "ACTIVE" },
        { registration_number: "UV-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000174", engine_number: "ENG000174", status: "ACTIVE" },
        { registration_number: "UV-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000175", engine_number: "ENG000175", status: "INACTIVE" },
        { registration_number: "UV-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000176", engine_number: "ENG000176", status: "ACTIVE" },
        { registration_number: "UV-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000177", engine_number: "ENG000177", status: "ACTIVE" },
        { registration_number: "UV-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000178", engine_number: "ENG000178", status: "ACTIVE" },
        { registration_number: "UV-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000179", engine_number: "ENG000179", status: "ACTIVE" },
        { registration_number: "UV-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000180", engine_number: "ENG000180", status: "UNDER_MAINTENANCE" },
        { registration_number: "UV-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000181", engine_number: "ENG000181", status: "ACTIVE" },
        { registration_number: "UV-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000182", engine_number: "ENG000182", status: "ACTIVE" },
        { registration_number: "UV-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000183", engine_number: "ENG000183", status: "ACTIVE" },
        { registration_number: "UV-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000184", engine_number: "ENG000184", status: "ACTIVE" },

        // Sabaragamuwa Province — 16 vehicles (SB-3-0001 to SB-3-0016)
        { registration_number: "SB-3-0001", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000185", engine_number: "ENG000185", status: "INACTIVE" },
        { registration_number: "SB-3-0002", vehicle_type: "Three Wheeler", model: "TVS King", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000186", engine_number: "ENG000186", status: "ACTIVE" },
        { registration_number: "SB-3-0003", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Red", year_of_manufacture: 2014, chassis_number: "CHS000187", engine_number: "ENG000187", status: "ACTIVE" },
        { registration_number: "SB-3-0004", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Silver", year_of_manufacture: 2015, chassis_number: "CHS000188", engine_number: "ENG000188", status: "ACTIVE" },
        { registration_number: "SB-3-0005", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Orange", year_of_manufacture: 2016, chassis_number: "CHS000189", engine_number: "ENG000189", status: "ACTIVE" },
        { registration_number: "SB-3-0006", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Yellow", year_of_manufacture: 2017, chassis_number: "CHS000190", engine_number: "ENG000190", status: "UNDER_MAINTENANCE" },
        { registration_number: "SB-3-0007", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Blue", year_of_manufacture: 2018, chassis_number: "CHS000191", engine_number: "ENG000191", status: "ACTIVE" },
        { registration_number: "SB-3-0008", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "Green", year_of_manufacture: 2019, chassis_number: "CHS000192", engine_number: "ENG000192", status: "ACTIVE" },
        { registration_number: "SB-3-0009", vehicle_type: "Three Wheeler", model: "Bajaj RE", color: "White", year_of_manufacture: 2020, chassis_number: "CHS000193", engine_number: "ENG000193", status: "ACTIVE" },
        { registration_number: "SB-3-0010", vehicle_type: "Three Wheeler", model: "TVS King", color: "Red", year_of_manufacture: 2021, chassis_number: "CHS000194", engine_number: "ENG000194", status: "ACTIVE" },
        { registration_number: "SB-3-0011", vehicle_type: "Three Wheeler", model: "Bajaj Compact RE", color: "Silver", year_of_manufacture: 2022, chassis_number: "CHS000195", engine_number: "ENG000195", status: "INACTIVE" },
        { registration_number: "SB-3-0012", vehicle_type: "Three Wheeler", model: "TVS King Deluxe", color: "Orange", year_of_manufacture: 2023, chassis_number: "CHS000196", engine_number: "ENG000196", status: "ACTIVE" },
        { registration_number: "SB-3-0013", vehicle_type: "Three Wheeler", model: "Piaggio Ape City", color: "Yellow", year_of_manufacture: 2010, chassis_number: "CHS000197", engine_number: "ENG000197", status: "ACTIVE" },
        { registration_number: "SB-3-0014", vehicle_type: "Three Wheeler", model: "Bajaj RE 4S", color: "Blue", year_of_manufacture: 2011, chassis_number: "CHS000198", engine_number: "ENG000198", status: "ACTIVE" },
        { registration_number: "SB-3-0015", vehicle_type: "Three Wheeler", model: "TVS King Duramax", color: "Green", year_of_manufacture: 2012, chassis_number: "CHS000199", engine_number: "ENG000199", status: "ACTIVE" },
        { registration_number: "SB-3-0016", vehicle_type: "Three Wheeler", model: "Bajaj RE EV", color: "White", year_of_manufacture: 2013, chassis_number: "CHS000200", engine_number: "ENG000200", status: "UNDER_MAINTENANCE" }
      ],
      { ignoreDuplicates: true }
    );

    console.log("200 vehicles seeded successfully");
  } catch (err) {
    console.error("Error seeding vehicles:", err);
  }
};

module.exports = seedVehicles;
